version: '3.8'

services:
  django:
    build: ./django
    image: django
    container_name: django
    env_file: .env
    networks:
      - transcendence
    volumes:
      - django_vol:/home
      - root_vol:/st
    ports:
        - "8000:8000"
        
  nginx:
    build: ./nginx
    image: nginx
    container_name: nginx
    env_file: .env
    networks:
      - transcendence
    volumes:
        - nginx_conf:/etc/nginx/conf.d
        - static_vol:/home/staticfiles
    ports:
      - "8080:8080"

  postgres:
    image: postgres:17-alpine3.20
    container_name: postgres
    env_file: .env
    networks:
      - transcendence
    volumes:
      - postgres_vol:/var/lib/postgresql/data
      - root_vol:/home
    ports:
     - "5432:5432"
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
    #   interval: 1s
    #   timeout: 1s
    #   retries: 5
    #   start_period: 1s

  redis:
    image: redis:7.4.1-alpine3.20
    container_name: redis
    networks:
      - transcendence
    ports:
      - "6380:6379"

networks:
  transcendence:
    name: tsen
    driver: bridge
    
volumes:
  django_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/django/django_vol

  nginx_conf:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/nginx/nginx_conf

  static_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/django/django_vol/staticfiles

  postgres_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/postgre/postgres_vol

  root_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}